service:
  name: lambda-prerender-service

frameworkVersion: ">=1.6.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: eu-north-1
  memorySize: 2048
  timeout: 20
  versionFunctions: false

custom:
  objectPrefix: "${self:service}-${self:provider.stage}"

functions:
  prerender:
    handler: functions/prerender.handler
    description: Prerender page provided with URL query parameter
    environment:
      DEBUG: 0
    events:
      - http:
          path: prerender
          method: get
